{% set data = load_setup_py_data(setup_file='../../setup.py', from_recipe_dir=True) %}
{% set name = "xarray-behave" %}
{% set version = data.get('version') %}

package:
  name: xarray-behave-nogui
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

build:
  number: 0

requirements:
  host:
    - defopt
    - flammkuchen
    - h5py
    - numpy
    - scipy
    - pandas
    - peakutils
    - pip
    - python
    - zarr
    - xarray
    - dask
    - pyvideoreader
    - setuptools
    - pysoundfile
    - libsndfile
    - samplestamps

  run:
    - defopt
    - flammkuchen
    - h5py
    - numpy
    - scipy
    - pandas
    - peakutils
    - pip
    - python
    - zarr
    - xarray
    - dask
    - pyvideoreader
    - setuptools
    - pysoundfile
    - libsndfile
    - samplestamps

test:
  imports:
    - xarray_behave

about:
  home: "http://github.com/janclemenslab/xarray-behave"
  license: MIT
  license_family: MIT
  license_file:
  summary: "xarray-behave"
  doc_url: "https://janclemenslab.org/das"
  dev_url: "http://github.com/janclemenslab/xarray-behave"

extra:
  recipe-maintainers:
    - postpop
