{% set data = load_setup_py_data(setup_file='../../setup.py', from_recipe_dir=True) %}
{% set name = data.get('name') %}
{% set version = data.get('version') %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

build:
  number: 0

requirements:
  host:
    - python {{ python }}
    - pip
  run:
    - python {{ python }}
    - defopt=6.3
    - rich
    - flammkuchen
    - h5py
    - pyyaml
    - zarr
    - numba
    - xarray
    - dask
    - librosa>0.8
    - pysoundfile
    - python-sounddevice
    - matplotlib
    - colorcet
    - pandas
    - scipy>=1.9
    - scikit-image
    - scikit-learn
    - peakutils
    - pyside6
    - pyqtgraph>0.12
    - qtpy
    - superqt
    - ffmpeg
    - pyvideoreader

about:
  home: "http://github.com/janclemenslab/xarray-behave"
  license: MIT
  license_family: MIT
  license_file:
  summary: "xarray behave"
  doc_url: "https://janclemenslab.org/xarray-behave"
  dev_url: "http://github.com/janclemenslab/xarray-behave"

extra:
  recipe-maintainers:
    - postpop
