{% set data = load_setup_py_data(setup_file='../../setup.py', from_recipe_dir=True) %}
{% set name = data.get('name') %}
{% set version = data.get('version') %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

build:
  number: 0

requirements:
  host:
    - python {{ python }}
    - pip
    - numpy<1.24
  run:
    - python {{ python }}
    - defopt=6.3
    - flammkuchen
    - h5py
    - librosa>0.8
    - matplotlib
    - matplotlib-scalebar
    - pandas
    - peakutils
    - pyyaml
    - scikit-learn
    - zarr
    - numba>=0.56
    - xarray
    - dask
    - pyside2 # [not win]
    - pyside6 # [win and py>39]
    - pyside2 # [win and py==39]
    - pyqtgraph>0.12.2
    - qtpy
    - superqt
    - rich
    - colorcet
    - python-sounddevice
    - scikit-image
    - opencv
    - ffmpeg
    - pyvideoreader
    - samplestamps
    - pysoundfile

test:
  imports:
    - xarray_behave
  commands:
    - xb --help [ not win ]

about:
  home: "http://github.com/janclemenslab/xarray-behave"
  license: MIT
  license_family: MIT
  license_file:
  summary: "xarray behave"
  doc_url: "https://janclemenslab.org/xarray-behave"
  dev_url: "http://github.com/janclemenslab/xarray-behave"

extra:
  recipe-maintainers:
    - postpop
